version: '2'

services:

  ################
  #FIRST SHARD
  ################

  mongodb_replset_1:
    image: marcob/mongodb-3.4.0-rc3
    labels:
      - "role=mongod"
      - "replset=rs1"


  ################
  #SECOND SHARD
  ################
  mongodb_replset_2:
    image: marcob/mongodb-3.4.0-rc3
    labels:
      - "role=mongod"
      - "replset=rs2"

  ################
  #THIRD SHARD
  ################
  mongodb_replset_3:
    image: marcob/mongodb-3.4.0-rc3
    labels:
      - "role=mongod"
      - "replset=rs3"

  ################
  #CFG SVR
  ################
  mongodb_cfg:
    image: marcob/mongodb-3.4.0-rc3
    labels:
      - "role=cfgsvr"


  ################
  #mongos
  ################
  mongodb_mongos:
    image: marcob/mongodb-3.4.0-rc3
    labels:
      - "role=mongos"
